Pin fossa-action version
dapr/kit pull request #15
Opened 2022-04-19 09:37 UTC by shubham1172

Signed-off-by: Shubham Sharma <shubhash@microsoft.com>

# Description

Due to a recent regression in FOSSA action's main branch, we are moving to the last working version.

## Issue reference

Related to: https://github.com/dapr/dapr/issues/4523

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests

2022-04-20 23:27 UTC, artursouza approved these changes

2022-04-20 23:28 UTC, artursouza requested changes
Please, fix lint in workflow too so we can merge this PR.

2022-04-20 23:54 UTC, artursouza approved these changes

2022-04-20 23:57 UTC, merged

2022-04-21 02:36 UTC, shubham1172 commented
@artursouza you can close this too then https://github.com/dapr/kit/issues/16