/events: Move `WithClock` to `unit` build tagged file
dapr/kit pull request #63
Opened 2023-10-12 09:24 UTC by JoshVanL

Reverts https://github.com/dapr/kit/pull/62

`WithClock` should be moved to `unit` build tagged files to not pollute implementation non-test builds. Developers wanting to override the clock in testing can do so by `go test`ing with the `unit` build tag.

2023-10-12 14:36 UTC, ItalyPaleAle requested changes
#62 was made on purpose. Please don’t reverse this.

2023-10-12 16:23 UTC, JoshVanL commented
> #62 was made on purpose. Please don’t reverse this.

I don't see the technical reason for needing `WithClock` in the implementation code. The mock code is still available in tests with the `unit` build tag.

2023-10-13 08:27 UTC, daixiang0 commented on events/batcher/batcher_unit.go
> +//go:build unit
rename to `events/batcher/unit.go`

2023-10-13 08:27 UTC, daixiang0 commented on events/batcher/batcher_unit_test.go
> +// +build unit
Same as above

2023-10-13 08:45 UTC, JoshVanL commented on events/batcher/batcher_unit.go
> +//go:build unit
Done :+1:

2023-10-13 08:45 UTC, JoshVanL commented on events/batcher/batcher_unit_test.go
> +// +build unit
Done :+1:

2023-11-15 18:23 UTC, yaron2 commented
@JoshVanL please resolve the conflict

2023-11-15 18:26 UTC, JoshVanL commented
@yaron2 Done

2023-11-16 17:11 UTC, yaron2 commented
> > #62 was made on purpose. Please don’t reverse this.
> 
> I don't see the technical reason for needing `WithClock` in the implementation code. The mock code is still available in tests with the `unit` build tag.

@ItalyPaleAle please review this comment so we can decide how to move forward with this PR

2025-05-22 13:58 UTC, closed without merging